[package]
name = "athenacl"
version = "2.0.0"
edition = "2021"

[package.metadata.bundle]
name = "athenaCL"
identifier = "by.alestsurko.athenacl"
icon = ["resources/athenaCL.icns"]
resources = ["resources/SGM-v2.01-YamahaGrand-Guit-Bass-v2.7.sf2"]

[dependencies]
ahash = "0.8.11"
async-channel = "2.3.1"
cpal = "0.15.3"
env_logger = "0.11"
iced = { version = "0.13.1", features = ["canvas", "tokio", "wgpu"] }
iced_aw = "0.11"
iced_fonts = { version = "0.1.1", features = ["nerd"] }
log = "0.4"
midi-player = "0.2.1"
quick-xml = "0.31.0"
rfd = "0.14.0"
# it's git for now, because the version supporting aiff have not released yet
rodio = { git = "https://github.com/RustAudio/rodio.git", features = [
    "symphonia-all",
    "symphonia-aiff",
    "symphonia-alac",
] }
rustpython-pylib = { version = "0.4.0", features = ["freeze-stdlib"] }
rustpython-stdlib = "0.4.0"
rustpython-vm = { version = "0.4.0", features = ["freeze-stdlib"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.64"

[build-dependencies]
serde_json = "1"

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }

[lints.rustdoc]
broken_intra_doc_links = "deny"
bare_urls = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }

# Don't panic.
string_slice = "warn"
indexing_slicing = "warn"
dbg_macro = "warn"
unwrap_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
get_unwrap = "warn"
unwrap_in_result = "warn"
unchecked_time_subtraction = "warn"
panic_in_result_fn = "warn"

# Don't fail silently.
let_underscore_future = "warn"
let_underscore_must_use = "warn"
unused_result_ok = "warn"
map_err_ignore = "warn"
assertions_on_result_states = "warn"

# Don't do bad async stuff.
await_holding_lock = "warn"
await_holding_refcell_ref = "warn"
if_let_mutex = "warn"
large_futures = "warn"

# Don't do unsafe things with memory.
mem_forget = "warn"
undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "warn"
unnecessary_safety_doc = "warn"
unnecessary_safety_comment = "warn"

# Don't do potentially incorrect things with numbers.
float_cmp = "warn"
float_cmp_const = "warn"
lossy_float_literal = "warn"
cast_sign_loss = "warn"
invalid_upcast_comparisons = "warn"

# Don't do bad things that are easy to avoid.
rc_mutex = "warn"
debug_assert_with_mut_call = "warn"
iter_not_returning_iterator = "warn"
expl_impl_clone_on_copy = "warn"
infallible_try_from = "warn"

# Require intentional lint suppressions.
allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 2 # rustpython is too slow in debug mode, so we enable -O2
